app:
  jwt:
    secret-key: ${JWT_SECRET_KEY:SuperSecret123}
    expires-in: ${JWT_EXPIRES_IN:3600000}

spring:
  application:
    name: spring-security
  datasource:
    url: jdbc:h2:mem:localdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
  h2:
    console:
      enabled: true
      path: /h2-console
